[package]
name = "pseudokafka"
version = "0.1.0"
authors = ["Ãlvaro Castro Castilla <a@fourthbit.com>"]
edition = "2018"

[dependencies]
byteorder = "1.4.2"
nom = "6.1.0"
num-derive = "0.3.3"
num-traits = "0.2.14"

[[bin]]
name = "pseudokafka"
path = "main.rs"